version: '3.4'

services:
  airportsreviews:
    image: airportsreviews
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/reviewsdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update


  db:
    image: postgres:12.5
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=reviewsdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

